Symfony 4 upgrade
SURFnet/sp-dashboard pull request #562
Opened 2022-11-21 08:53 UTC by Shaky212

This is the upgrade from Symfony 3.4 tot Symfony 4.4. The major steps are:
- resolve deprecations
- upgrade composer to Symfony 4.4
- installl Symfony/flex 

Within Symfony 4 the application and directory structure has changed. The app folder has partly been moved to the config folder en the .env environment. All twig templates have been moved to the templates folder.

Notice the .env contains a parameter administrator_teams used in the dashboard_saml.yaml and checked during compile time in Configuration.php. Previously this was an array, but not supported because of it's dynamic character. The administrator_teams is now a scalar, a string with comma separated values.

See also: https://symfonycasts.com/screencast/symfony4-upgrade/upgrade4

2022-11-22 08:06 UTC, MKodde reviewed
Awesome work so far! I did note quiet a few issues you might need to address.

For example: 
- Some of the old, unused folders are still in the project `web`, `app`
- Swiftmailer is still showing up in config
- See code review below for more details.

2022-11-22 08:06 UTC, MKodde commented on src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
> -        $logger = $this->get('logger');
:mechanical_arm: :medal_military:

2022-11-22 08:06 UTC, MKodde commented on templates/Exception/error.html.twig
> +{% extends '../../../../../templates/base.html.twig' %}
Why are the `../` required here. Given the other templates that can simply extend the base template by its name?

2022-11-22 08:13 UTC, MKodde requested changes

2022-11-22 08:13 UTC, MKodde commented on docker/Dockerfiledev
> +#COPY ./conf/saml20_sp.json /tmp/saml20_sp.json
Also on line 13, we install composer 1 in the `fpm` container. But that conflicts with our new composer packages installed. They require composer 2 to install. Please upgrade to composer 2 :)

2022-11-22 08:14 UTC, MKodde commented
The jest test still fail as they refer to old, moved fixture files. Should be an easy fix to get a fully green build!

2022-12-09 10:20 UTC, quartje commented on docker/Dockerfile
> +RUN composer install -n --prefer-dist -o --ignore-platform-reqs --no-dev
Will this install the assets?

2023-01-04 07:28 UTC, closed without merging