Save the selected Types of service in Manage
SURFnet/sp-dashboard pull request #648
Opened 2024-07-01 13:19 UTC by MKodde

The form data is taken from the resulting command, stored on the ManageEntity. Which in turn is used to generate the metadata that is presented to Manage.

This PR also refactored the repository that tracks the local Type of Service values. That repository is now part of the domain logic.

https://www.pivotaltracker.com/story/show/186681044

2024-07-04 09:05 UTC, parijke requested changes
I cannot judge the business logic, but I have a few small recommendations on code quality and readability

2024-07-08 08:32 UTC, MKodde commented on src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngResourceServerEntityCommand.php
> +        return [];
This entity type does not support types of service selection. But it does implement the interface. Hence the empty function.

2024-07-08 08:53 UTC, MKodde commented on src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/SpDashboardMetadataGenerator.php
> +                case $attribute->id === 'typeOfService':
I do not feel there is a big benefit to using constants here. We refer to identifiers set in `assets/Resources/metadata/sp_dashboard.json`. Which the filename (and class setup) already implies. I'm not changing this, sorry.

2024-07-08 08:54 UTC, MKodde commented on src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/SpDashboardMetadataGenerator.php
> +                    if ($coin && $coin->$getterName() && count($coin->getTypeOfService()->getArray()) > 0) {
It might be a good idea to clarify this further. I'll rework this a bit!

2024-07-08 08:58 UTC, MKodde commented on src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php
> +        $typesOfService = new TypeOfServiceCollection();
You might be onto something here. But for explanations sake: The name was determined by the domain experts (TPM). I always try to reflect the ubiquitous language strictly in the domain of the application.

2024-07-08 08:59 UTC, MKodde commented on src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/Coin.php
> +        private ?TypeOfServiceCollection $typeOfService,
I messed around with pluralization a bit. In the end I settled on not pluralizing the concept. I will sync this throughout.

2024-07-08 09:30 UTC, MKodde commented on src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/TypeOfService.php
>          public string $typeEn,
TypeEn is mandatory, The dutch type is not.

2024-07-08 09:32 UTC, MKodde commented on src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/TypeOfServiceCollection.php
> +        $englishEntry = $metaDataFields['coin:ss:type_of_service:en'] ?? '';
A fair point. For now, and in the foreseeable future, we will only track EN and NL. When languages are added. I suggest we make this more robust.

2024-07-08 09:32 UTC, MKodde commented on src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/TypeOfServiceCollection.php
> +    public function has(string $englishTypeOfService): bool
The abbreviations I only used in tests.

2024-07-09 07:56 UTC, merged